"""
ZK cryptography helpers.

In production these run inside the browser via snarkJS WASM.
Here we replicate the same math in Python so the server can:
  - generate test identities
  - compute nullifiers for the seed students
  - build the fake Groth16 proof accepted by VerifierStub.sol

Hash: keccak256-based stub that matches PoseidonStub.sol on-chain.
"""
import hashlib
import logging
import secrets

logger = logging.getLogger("atomic-choice.zk")

SNARK_FIELD = (
    21888242871839275222246405745257275088548364400416034343698204186575808495617
)


# ── Hash stubs matching PoseidonStub.sol ──────────────────────────────────────

def poseidon1(x: int) -> int:
    """Poseidon(x) — identity commitment"""
    raw = x.to_bytes(32, "big")
    return int(hashlib.sha256(raw).hexdigest(), 16) % SNARK_FIELD


def poseidon2(a: int, b: int) -> int:
    """Poseidon(a, b) — nullifier hash"""
    raw = a.to_bytes(32, "big") + b.to_bytes(32, "big")
    return int(hashlib.sha256(raw).hexdigest(), 16) % SNARK_FIELD


# ── Identity helpers ───────────────────────────────────────────────────────────

def generate_secret() -> int:
    """Random 248-bit field element."""
    return int(secrets.token_hex(31), 16) % SNARK_FIELD


def commitment_of(secret: int) -> int:
    return poseidon1(secret)


def nullifier_of(secret: int, poll_id: int) -> int:
    return poseidon2(secret, poll_id)


# ── Fake Groth16 proof (accepted by VerifierStub) ─────────────────────────────

ZERO_PROOF = {
    "pA": [0, 0],
    "pB": [[0, 0], [0, 0]],
    "pC": [0, 0],
}


def make_stub_proof(nullifier: int, root: int, vote: int, poll_id: int) -> dict:
    """
    Returns a zeroed-out Groth16 proof that VerifierStub.sol will accept.
    In production this is generated by snarkJS in the browser.
    """
    return {
        "nullifierHash": nullifier,
        "merkleRoot": root,
        "vote": vote,
        "pollId": poll_id,
        **ZERO_PROOF,
    }


# ── Seed identities for test students ─────────────────────────────────────────
# Each student gets a deterministic secret derived from their wallet address.
# This makes the demo reproducible.

def student_secret(wallet: str) -> int:
    """Deterministic secret for a given wallet (demo only)."""
    raw = wallet.lower().encode()
    return int(hashlib.sha256(raw).hexdigest(), 16) % SNARK_FIELD
